TARGET = dist/ToolbitDMM-linux-x64/ToolbitDMM

# implementation

all: $(TARGET)

FORCE:

$(TARGET):
	@[ -d dist ] || mkdir -p dist
	cd dist; electron-packager ../src ToolbitDMM --platform=linux --arch=x64 --electronVersion=4.2.12

clean:
	rm -fr dist/ToolbitDMM-linux-x64


.PHONY: all clean
