TARGET = dist/ToolbitDMM-darwin-x64/ToolbitDMM.app

# implementation

all: $(TARGET)

FORCE:

$(TARGET):
	@[ -d dist ] || mkdir -p dist
	cd dist; electron-packager ../src ToolbitDMM --platform=darwin --arch=x64 --electronVersion=4.2.12

clean:
	rm -fr dist/ToolbitDMM-darwin-x64


.PHONY: all clean
