TARGET = dist/ToolbitDMM-win32-x64/ToolbitDMM.exe

# implementation

all: $(TARGET)

FORCE:

$(TARGET):
	@[ -d dist ] || mkdir -p dist
	cd dist; electron-packager ../src ToolbitDMM --platform=win32 --arch=x64 --electronVersion=4.2.12 --icon=../icon/icon.ico

clean:
	rm -fr dist/ToolbitDMM-win32-x64


.PHONY: all clean
