name: Toolbit DMM app CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: |
        cd src; npm install

    - name: Make binary
      run: |
        npm install -g electron-packager
        make

    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
       name: ToolibtDMM-binary-dist
       path: dist

#    - name: npm install, build, and test
#      run: |
#        npm ci
#        npm run build --if-present
#        npm test
#      env:
#        CI: true
